import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "Category",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body className={`bg-green-400 dark:bg-yellow-400`}>
                <h2>Something</h2>
                {children}
            </body>
        </html>
    );
}

// 🔥 Next.js 14 Tutorial - 16 - Route Group Layout 🔥